# -*- coding: utf-8 -*-
"""BARAN TEKEMEN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y9N4VCHklebBFJA209QZp6whveq9RipD
"""

!pip install tensorflow

#KÜTÜPHANELER
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

from sklearn.metrics import confusion_matrix, roc_curve, auc
from sklearn.metrics import classification_report

#PARAMETRELER
np.random.seed(42)
time_steps = 60
features = 3

#VERİ OLUŞTURMA
X = np.random.rand(1000, time_steps, features)

#FİZYOLOJİK ARALIKLARA ÖLÇEKLEME
hr = X[:,:,0] * 40 + 60
spo2 = X[:,:,1] * 5 + 95
ecg = X[:,:,2]

#X İÇERİSİNE YERLEŞTİRMEK
X[:,:,0] = hr
X[:,:,1] = spo2
X[:,:,2] = ecg

# NORMALİZASYON
X = X / np.max(X)

# ETİKET OLUŞTURMAK
risk_signal = (hr.mean(axis=1) > 85) | (spo2.mean(axis=1) < 96)
y = risk_signal.astype(int)

print("Sınıf dağılımı:")
print("Sağlıklı (0):", np.sum(y == 0))
print("Riskli (1):", np.sum(y == 1))

#KRİZ SİMÜLASYONU
for i in range(300):  # 200 TANE KRİZLİ VERİ OLUŞTUR
    idx = np.random.randint(0, 1000)

    # SON 10 TİMESTEPTE KRİZ OLUŞTUR
    X[idx, -10:, 0] = np.random.uniform(110, 140, 10)  # yüksek nabız
    X[idx, -10:, 1] = np.random.uniform(85, 92, 10)    # düşük oksijen

    y[idx] = 1  # risk = 1


# TRAİN / TEST AYRIMI
split = int(0.8 * len(X))
X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

#MODEL OLUŞTURMA
model = Sequential([
    LSTM(64, return_sequences=True, input_shape=(time_steps, features)),
    Dropout(0.2),
    LSTM(32),
    Dense(16, activation='relu'),
    Dropout(0.1),
    Dense(1, activation='sigmoid')
])
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

#MODEL EĞİTİMİ
early_stop = EarlyStopping(patience=3, restore_best_weights=True)

history = model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=32,
    validation_data=(X_test, y_test),
    callbacks=[early_stop],
    class_weight={0:1, 1:2}
)
#MODEL DEĞERLENDİRME
y_pred = model.predict(X_test)
y_pred_class = (y_pred > 0.35).astype(int)

#CONFUSİON MATRİX
cm = confusion_matrix(y_test, y_pred_class)
sns.heatmap(cm, annot=True, fmt="d")
plt.title("Confusion Matrix")
plt.xlabel("Tahmin")
plt.ylabel("Gerçek")
plt.show()

#ROC CURVE
fpr, tpr, thresholds = roc_curve(y_test, y_pred)
roc_auc = auc(fpr, tpr)

plt.plot(fpr, tpr, label="AUC = %.2f" % roc_auc)
plt.plot([0,1], [0,1], linestyle="--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

#GRAFİKLER(NORMAL/KRİZ)
normal_index = np.where(y == 0)[0][0]
crisis_index = np.where(y == 1)[0][0]
#NORMAL
plt.plot(X[normal_index,:,0], label="HR Normal")
plt.plot(X[normal_index,:,1], label="SpO2 Normal")
plt.title("Normal Fizyolojik Durum")
plt.legend()
plt.show()

#KRİZ
plt.plot(X[crisis_index,:,0], label="HR")
plt.plot(X[crisis_index,:,1], label="SpO2")
plt.title("Kriz Anı (Ani Değişim)")
plt.legend()
plt.show()


#RAPOR
print(classification_report(y_test, y_pred_class))
print("ROC AUC:", roc_auc)