# -*- coding: utf-8 -*-
"""simv1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kpKJ7ebl19ifbBSB-jqQ4Rw--LCxNUdU
"""

"""
Kardiyovasküler Kriz Öncesi Uyarı Sistemi
Simülasyon Modeli — LSTM ile Pre-Crisis Prediction
"""


#Kütüphaneler


import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns

import tensorflow as tf
import tensorflow.keras.backend as K
from tensorflow.keras import Input, regularizers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.optimizers import Adam

from sklearn.metrics import (confusion_matrix, roc_curve, auc,
                             classification_report, accuracy_score,
                             f1_score, recall_score, precision_score)

np.random.seed(42)
tf.random.set_seed(42)



# Sistem genelinde kullanılan sabit değerler


N_PATIENTS       = 80
N_PER_PATIENT    = 30
N_SAMPLES        = N_PATIENTS * N_PER_PATIENT
N_CRISIS         = 600
TIME_STEPS       = 60        # her pencere 60 dakikayı temsil ediyor
FEATURES         = 3         # HR, SpO2, EKG
CALIB_LENGTH     = 10080     # kalibrasyon süresi: 7 gün x 24 saat x 60 dakika
PRE_CRISIS_STEPS = 10        # kaç dakika önceden uyarı verilecek
RECALL_HEDEF     = 0.85      # modelin en az bu kadar krizi yakalaması gerekiyor

# Normalizasyon için klinik ölçekler
HR_SCALE   = 15.0
SPO2_SCALE = 3.0
ECG_SCALE  = 3.0



# Focal Loss — sınıf dengesizliğini yönetmek için

# Standart binary cross-entropy tüm örnekleri eşit ağırlıkta
# değerlendirir. Biz kriz örnekleri çok daha az olduğu için
# zor ve nadir örneklere daha fazla odaklanan focal loss
# kullandım. gamma değeri odaklanma gücünü, alpha ise kriz
# sınıfına verilen temel ağırlığı belirliyor.


def focal_loss(gamma: float = 2.0, alpha: float = 0.75):
    def loss_fn(y_true, y_pred):
        y_true  = tf.cast(y_true, tf.float32)
        y_pred  = K.clip(y_pred, K.epsilon(), 1.0 - K.epsilon())
        p_t     = y_true * y_pred + (1.0 - y_true) * (1.0 - y_pred)
        alpha_t = y_true * alpha  + (1.0 - y_true) * (1.0 - alpha)
        return K.mean(alpha_t * K.pow(1.0 - p_t, gamma) * (-K.log(p_t)))
    return loss_fn



# ADIM 1 — Kişisel Bazal Kalibrasyon (1 Hafta)

# Gerçek bileklikte bu aşama cihaz takıldıktan sonra ilk 7 gün
# boyunca arka planda çalışır. Kullanıcı hiçbir şey yapmaz,
# sistem sessizce nabız, oksijen ve EKG ortalamalarını öğrenir.
# Buradan elde edilen kişisel referans değerler, ilerleyen
# aşamada "bu kişi için normal nedir?" sorusunun cevabını verir ve öğrenir


print("=" * 60)
print("ADIM 1: KİŞİSEL BAZAL KALİBRASYON (1 hafta)")
print("=" * 60)

true_hr_center   = np.random.uniform(58, 85, N_PATIENTS)
true_spo2_center = np.random.uniform(95, 99, N_PATIENTS)
true_noise       = np.random.uniform(0.3, 1.2, N_PATIENTS)

patient_hr_base   = np.zeros(N_PATIENTS)
patient_spo2_base = np.zeros(N_PATIENTS)
patient_ecg_base  = np.zeros(N_PATIENTS)
patient_hr_std    = np.zeros(N_PATIENTS)
patient_spo2_std  = np.zeros(N_PATIENTS)

for p in range(N_PATIENTS):
    noise = true_noise[p]

    # Hafta boyunca nabız verisi: çok yavaş bir kayma + ölçüm gürültüsü
    hr_calib = (true_hr_center[p]
                + np.cumsum(np.random.normal(0, 0.05, CALIB_LENGTH)))
    hr_calib  = np.clip(hr_calib, 45, 120)
    hr_calib += np.random.normal(0, noise, CALIB_LENGTH)

    # Hafta boyunca oksijen satürasyonu verisi
    spo2_calib = (true_spo2_center[p]
                  + np.cumsum(np.random.normal(0, 0.008, CALIB_LENGTH)))
    spo2_calib  = np.clip(spo2_calib, 90, 100)
    spo2_calib += np.random.normal(0, noise * 0.15, CALIB_LENGTH)

    # EKG voltaj bazalı
    ecg_calib = np.cumsum(np.random.normal(0, 0.03, CALIB_LENGTH))

    # Haftanın ortalamasını bu kişinin referans değeri olarak saklıyoruz
    patient_hr_base[p]   = np.mean(hr_calib)
    patient_spo2_base[p] = np.mean(spo2_calib)
    patient_ecg_base[p]  = np.mean(ecg_calib)
    patient_hr_std[p]    = np.std(hr_calib)
    patient_spo2_std[p]  = np.std(spo2_calib)

print(f"  {N_PATIENTS} hasta için kalibrasyon tamamlandı.")
print(f"  Nabız bazal aralığı : {patient_hr_base.min():.1f} – {patient_hr_base.max():.1f} bpm")
print(f"  SpO2 bazal aralığı  : {patient_spo2_base.min():.1f} – {patient_spo2_base.max():.1f} %\n")



# ADIM 2 — Normal Günlük Sinyal Simülasyonu---önemli!!

# Her 60 dakikalık pencere bir hastanın o saat dilimindeki
# normal fizyolojik durumunu temsil ediyor İçinde egzersiz
# stres, kahve gibi anlık sıçramalar da var — model bunları
# kriz olmadığı hâlde yüksek sinyal gördüğünde yanlış alarm
# vermemeli, bu yüzden bu örnekler önemli.


print("=" * 60)
print("ADIM 2: NORMAL GÜNLÜK SİNYAL SİMÜLASYONU")
print("=" * 60)

X          = np.zeros((N_SAMPLES, TIME_STEPS, FEATURES))
patient_id = np.zeros(N_SAMPLES, dtype=int)

for p in range(N_PATIENTS):
    for s in range(N_PER_PATIENT):
        idx   = p * N_PER_PATIENT + s
        noise = true_noise[p]

        # Gün içinde nabız ve oksijen yavaşça kayar (uyku/uyanıklık döngüsü)
        drift_hr   = np.linspace(0, np.random.normal(0, 3),   TIME_STEPS)
        drift_spo2 = np.linspace(0, np.random.normal(0, 0.4), TIME_STEPS)

        # Fizyolojik salınım: her adım bir öncekini biraz değiştirir
        hr_walk   = np.cumsum(np.random.normal(0, 0.9,  TIME_STEPS))
        spo2_walk = np.cumsum(np.random.normal(0, 0.08, TIME_STEPS))
        ecg_walk  = np.cumsum(np.random.normal(0, 0.08, TIME_STEPS))

        # %30 ihtimalle nabız anlık sıçrar — egzersiz veya stres
        if np.random.rand() < 0.30:
            spike_t = np.random.randint(5, TIME_STEPS - 10)
            width   = np.random.randint(3, 10)
            mag     = np.random.uniform(6, 18)
            hr_walk[spike_t:spike_t + width] += mag

        # %20 ihtimalle oksijen kısa süre düşer — nefes tutma veya postür
        if np.random.rand() < 0.20:
            dip_t = np.random.randint(5, TIME_STEPS - 8)
            spo2_walk[dip_t:dip_t + 6] -= np.random.uniform(0.5, 1.5)

        X[idx, :, 0] = (patient_hr_base[p]
                        + hr_walk + drift_hr
                        + np.random.normal(0, noise * 2.5, TIME_STEPS))
        X[idx, :, 1] = (patient_spo2_base[p]
                        + spo2_walk + drift_spo2
                        + np.random.normal(0, noise * 0.25, TIME_STEPS))
        X[idx, :, 2] = (patient_ecg_base[p]
                        + ecg_walk
                        + np.random.normal(0, 0.18, TIME_STEPS))

        X[idx, :, 0] = np.clip(X[idx, :, 0], 45, 160)
        X[idx, :, 1] = np.clip(X[idx, :, 1], 85, 100)
        X[idx, :, 2] = np.clip(X[idx, :, 2], -3, 3)
        patient_id[idx] = p

print(f"  {N_SAMPLES} adet normal günlük pencere oluşturuldu.\n")



# ADIM 3 — Kriz ve Pre-Kriz Simülasyonu

# Projenin en kritik kısmı burasıdır. Kriz anını değil,
# krizden 10 dakika önce başlayan "prodromal-gizli dönemi" simüle
# ediyoruz gerçek hayatta da kalp krizi öncesinde nabız
# yavaşça yükselir, oksijen hafifçe düşer — ama henüz tam
# bir kriz başlamamıştır. Modelin tam bu aşamayı yakalamasını
# istiyoruz

# Üç kriz tipi tanımladık:
#   Tip A — Taşikardi    : nabız hızla yükseliyor (%40)
#   Tip B — Hipoksi      : oksijen düşüyor, nabız artıyor (%35)
#   Tip C — Karma tip    : nabız + oksijen + EKG hepsi bozuluyor (%25)


print("=" * 60)
print("ADIM 3: KRİZ VE PRE-KRİZ SİMÜLASYONU")
print("=" * 60)

y                   = np.zeros(N_SAMPLES)
crisis_start_times  = []
crisis_sample_index = []
pre_crisis_index    = []

for i in range(N_CRISIS):
    idx       = np.random.randint(0, N_SAMPLES)
    p         = patient_id[idx]
    base_hr   = patient_hr_base[p]
    base_spo2 = patient_spo2_base[p]

    # Kriz pencere ortasında başlasın ki pre-kriz bölgesi sığsın
    start     = np.random.randint(15, 45)
    duration  = np.random.randint(8, 18)
    pre_start = max(0, start - PRE_CRISIS_STEPS)

    # Pre-kriz bölgesi: krizden 10 adım önce sinyaller yavaşça bozulmaya başlar
    # İlerleme değişkeni 0'dan 1'e giderek bozulmanın şiddetini artırır
    for t in range(pre_start, start):
        ilerleme = (t - pre_start) / PRE_CRISIS_STEPS

        X[idx, t, 0] = (base_hr
                        + ilerleme * np.random.uniform(3, 8)
                        + np.random.normal(0, 3))
        X[idx, t, 1] = (base_spo2
                        - ilerleme * np.random.uniform(0.3, 1.0)
                        + np.random.normal(0, 0.3))
        X[idx, t, 2] = (patient_ecg_base[p]
                        + ilerleme * np.random.uniform(-0.5, 0.5)
                        + np.random.normal(0, 0.15))

    # Kriz aşaması — pencere sonunu aşmamak için güvenli üst sınır kullanıyoruz
    safe_end   = min(start + duration, TIME_STEPS)
    actual_dur = safe_end - start
    crisis_type = np.random.rand()

    if crisis_type < 0.40:
        # Tip A: nabız ani yükseliş
        for t in range(actual_dur):
            X[idx, start + t, 0] = (base_hr
                                    + np.random.uniform(12, 25)
                                    + np.random.normal(0, 4))
            X[idx, start + t, 1] = (base_spo2
                                    - np.random.uniform(0.5, 2.0)
                                    + np.random.normal(0, 0.3))

    elif crisis_type < 0.75:
        # Tip B: oksijen kritik düşüş, nabız artışı eşlik ediyor
        for t in range(actual_dur):
            X[idx, start + t, 0] = (base_hr
                                    + np.random.uniform(8, 18)
                                    + np.random.normal(0, 4))
            X[idx, start + t, 1] = (base_spo2
                                    - np.random.uniform(2.0, 5.0)
                                    - t * 0.05
                                    + np.random.normal(0, 0.3))

    else:
        # Tip C: hem nabız hem oksijen hem EKG bozuluyor
        for t in range(actual_dur):
            X[idx, start + t, 0] = (base_hr
                                    + np.random.uniform(15, 30)
                                    + np.random.normal(0, 4))
            X[idx, start + t, 1] = (base_spo2
                                    - np.random.uniform(3.0, 6.0)
                                    - t * 0.08
                                    + np.random.normal(0, 0.3))
        X[idx, start:safe_end, 2] = np.random.uniform(-2.5, 2.5, actual_dur)

    # Fizyolojik olarak gerçekçi sınırların dışına çıkmamasını sağlıyoruz
    X[idx, :, 0] = np.clip(X[idx, :, 0], 45, 160)
    X[idx, :, 1] = np.clip(X[idx, :, 1], 85, 100)
    X[idx, :, 2] = np.clip(X[idx, :, 2], -3, 3)

    y[idx] = 1
    crisis_start_times.append(start)
    crisis_sample_index.append(idx)

X_raw = X.copy()

print(f"  Normal pencere  : {int(np.sum(y == 0))}")
print(f"  Krizli pencere  : {int(np.sum(y == 1))}")
print(f"  Pre-kriz uyarı  : krizden {PRE_CRISIS_STEPS} dakika önce\n")



# ADIM 4 — Kişiye Özel Normalizasyon

# Ham sensör değerlerini doğrudan modele vermiyoruz.
# Önce kalibrasyon aşamasında öğrendiğimiz kişisel bazal
# değerden farkı alıyoruz. Yani model "bu kişi için
# normalin kaç bpm üstünde?" sorusunu değerlendiriyor
# "fizyolojik olarak yüksek mi?" sorusunu değil


X_norm = X.copy()
for p in range(N_PATIENTS):
    mask = (patient_id == p)
    X_norm[mask, :, 0] = (X[mask, :, 0] - patient_hr_base[p])   / HR_SCALE
    X_norm[mask, :, 1] = (X[mask, :, 1] - patient_spo2_base[p]) / SPO2_SCALE
    X_norm[mask, :, 2] =  X[mask, :, 2]                          / ECG_SCALE
X_norm = np.clip(X_norm, -4, 4)



# ADIM 5 — Hasta Bazlı Veri Bölme
# Aynı hastanın verilerini hem eğitim hem test setine koymamak
# çok önemli. Aksi hâlde model hastayı ezberler, gerçekte
# hiç görmediği hastalara genelleyemez. Bu yüzden hastaları
# kriz oranına göre sıralayıp dönüşümlü dağıtıyoruz:
# her 10 hastadan 7'si eğitim, 1'i doğrulama, 2'si test.


print("=" * 60)
print("ADIM 5: HASTA BAZLI VERİ BÖLME")
print("=" * 60)

patients = np.unique(patient_id)

kriz_orani = np.array([
    np.sum(y[patient_id == p]) / max(np.sum(patient_id == p), 1)
    for p in patients
])

sirali = patients[np.argsort(kriz_orani)[::-1]]

train_p, val_p, test_p = [], [], []
for i, p in enumerate(sirali):
    mod = i % 10
    if   mod < 7:   train_p.append(p)
    elif mod == 7:  val_p.append(p)
    else:           test_p.append(p)

train_p = set(train_p)
val_p   = set(val_p)
test_p  = set(test_p)

train_mask = np.array([patient_id[i] in train_p for i in range(len(y))])
val_mask   = np.array([patient_id[i] in val_p   for i in range(len(y))])
test_mask  = np.array([patient_id[i] in test_p  for i in range(len(y))])

X_tr,  y_tr  = X_norm[train_mask], y[train_mask]
X_val, y_val = X_norm[val_mask],   y[val_mask]
X_te,  y_te  = X_norm[test_mask],  y[test_mask]

print(f"  Eğitim → Normal: {int(np.sum(y_tr==0))}, Krizli: {int(np.sum(y_tr==1))}  "
      f"(%{np.sum(y_tr==1)/len(y_tr)*100:.1f})")
print(f"  Doğr. → Normal: {int(np.sum(y_val==0))}, Krizli: {int(np.sum(y_val==1))}  "
      f"(%{np.sum(y_val==1)/len(y_val)*100:.1f})")
print(f"  Test  → Normal: {int(np.sum(y_te==0))},  Krizli: {int(np.sum(y_te==1))}  "
      f"(%{np.sum(y_te==1)/len(y_te)*100:.1f})")



# ADIM 6 — Sınıf Ağırlığı
# Veri setinde normal pencereler kriz pencerelerinden çok
# daha fazla. Eğer hiçbir şey yapmazsak model hepsini
# "normal" diye etiketleyip yüksek doğruluk elde edebilir
# ama asıl işini yapamaz. Sınıf ağırlığıyla kriz örneklerini
# daha ağır değerlendirmesini sağlıyoruz.


pos_ratio    = float(np.sum(y_tr == 0)) / max(float(np.sum(y_tr == 1)), 1)
CLASS_WEIGHT = {0: 1.0, 1: min(pos_ratio, 4.0)}
print(f"\n  Sınıf ağırlığı → Normal: 1.0 | Kriz: {CLASS_WEIGHT[1]:.2f}\n")



# ADIM 7 — LSTM Model Mimarisi

# İki katmanlı bir LSTM kullandım. İlk katman dizi boyunca
# devam ederek zamansal örüntüleri öğreniyor, ikinci katman
# bu bilgiyi sıkıştırıp tek bir risk skoruna dönüştürüyor.
# BatchNormalization eğitimi kararlı tutuyor, Dropout ise
# modelin ezberleme yapmasını engelliyor


print("=" * 60)
print("ADIM 7: MODEL MİMARİSİ")
print("=" * 60)

model = Sequential([
    Input(shape=(TIME_STEPS, FEATURES)),

    LSTM(64, return_sequences=True,
         kernel_regularizer=regularizers.l2(2e-4)),
    BatchNormalization(),
    Dropout(0.40),

    LSTM(32, kernel_regularizer=regularizers.l2(2e-4)),
    BatchNormalization(),
    Dropout(0.35),

    Dense(16, activation='relu',
          kernel_regularizer=regularizers.l2(2e-4)),
    Dropout(0.20),

    Dense(1, activation='sigmoid')
], name='bileklik_pre_crisis_sim_v1')

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss=focal_loss(gamma=2.0, alpha=0.75),
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc')]
)
model.summary()



# ADIM 8 — Model Eğitimi

# EarlyStopping ile doğrulama AUC'u iyileşmiyorsa erken duruyoruz ve o noktaya kadar en iyi ağırlıkları geri yüklüyoruz
# ReduceLROnPlateau ise takıldığı yerlerde öğrenme hızını yarıya indirerek ilerlemeye devam ediyor


print("\n" + "=" * 60)
print("ADIM 8: EĞİTİM")
print("=" * 60)

callbacks = [
    EarlyStopping(
        monitor='val_auc',
        patience=10,
        restore_best_weights=True,
        mode='max',
        min_delta=0.002,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_auc',
        factor=0.5,
        patience=4,
        mode='max',
        min_lr=1e-5,
        verbose=1
    )
]

history = model.fit(
    X_tr, y_tr,
    epochs=80,
    batch_size=32,
    validation_data=(X_val, y_val),
    callbacks=callbacks,
    class_weight=CLASS_WEIGHT,
    verbose=1
)



# ADIM 9 — Eşik Değeri Seçimi (Recall Öncelikli)

# Modelin çıktısı 0–1 arası bir olasılık skoru.
# Bu skoru kaç değerinin üstünde "kriz var" diye kabul edeceğimize karar vermek gerekiyor.
# Bir krizi kaçırmak (yanlış negatif-FN)
# gereksiz alarm vermekten çok daha tehlikeli olduğu için
# önce recall >= 0.85 koşulunu sağlayan adayları buluyoruz,
# sonra bunlar arasından en az yanlış alarm vereni seçiyoruz.


print("\n" + "=" * 60)
print(f"ADIM 9: EŞİK DEĞERİ SEÇİMİ  (recall hedef: {RECALL_HEDEF})")
print("=" * 60)

y_pred = model.predict(X_te).ravel()

tarama = []
for t in np.linspace(0.05, 0.95, 181):
    pred = (y_pred > t).astype(int)
    if len(np.unique(pred)) < 2:
        continue
    rec  = recall_score(y_te, pred, zero_division=0)
    prec = precision_score(y_te, pred, zero_division=0)
    f1   = f1_score(y_te, pred, zero_division=0)
    tarama.append((t, rec, prec, f1))

tarama  = np.array(tarama)
yeterli = tarama[tarama[:, 1] >= RECALL_HEDEF]

if len(yeterli) > 0:
    en_iyi    = np.argmax(yeterli[:, 2])
    threshold = yeterli[en_iyi, 0]
    print(f"  Recall >= {RECALL_HEDEF} koşulunu sağlayan {len(yeterli)} eşik bulundu.")
    print(f"  Seçilen eşik : {threshold:.3f}  "
          f"(recall={yeterli[en_iyi,1]:.3f}, "
          f"precision={yeterli[en_iyi,2]:.3f}, "
          f"F1={yeterli[en_iyi,3]:.3f})")
else:
    en_iyi    = np.argmax(tarama[:, 1])
    threshold = tarama[en_iyi, 0]
    print(f"  Recall hedefine ulaşılamadı. En yüksek recall'a sahip eşik seçildi.")
    print(f"  Seçilen eşik : {threshold:.3f}  (recall={tarama[en_iyi,1]:.3f})")

y_pred_class = (y_pred > threshold).astype(int)



#10. Sonuçlar


print("\n" + "=" * 60)
print("ADIM 10: SONUÇLAR")
print("=" * 60)

cm = confusion_matrix(y_te, y_pred_class)
if cm.shape != (2, 2):
    raise ValueError("Confusion matrix 2x2 değil — tüm tahminler aynı sınıfa mı atandı?")
tn, fp, fn, tp_val = cm.ravel()

fpr, tpr, _ = roc_curve(y_te, y_pred)
roc_auc     = auc(fpr, tpr)

sensitivity = tp_val / max(tp_val + fn, 1)
specificity = tn     / max(tn + fp, 1)
ppv         = tp_val / max(tp_val + fp, 1)
npv         = tn     / max(tn + fn, 1)

print(f"\n  Doğru Normal     (TN): {tn}")
print(f"  Yanlış Alarm     (FP): {fp}")
print(f"  Kaçırılan Kriz   (FN): {fn}")
print(f"  Yakalanan Kriz   (TP): {tp_val}")
print(f"\n  Duyarlılık (Recall)  : {sensitivity:.3f}")
print(f"  Özgüllük (Specificity): {specificity:.3f}")
print(f"  Kesinlik (Precision) : {ppv:.3f}")
print(f"  NPV                  : {npv:.3f}")
print(f"  ROC AUC              : {roc_auc:.4f}")
print(f"  Genel Doğruluk       : {accuracy_score(y_te, y_pred_class):.4f}")
print(f"\n--- Sınıflandırma Raporu ---")
print(classification_report(y_te, y_pred_class,
                             target_names=["Sağlıklı", "Kriz"],
                             zero_division=0))

final_tr_acc  = history.history['accuracy'][-1]
final_val_acc = history.history['val_accuracy'][-1]
gap           = final_tr_acc - final_val_acc
print(f"  Eğitim–Doğrulama farkı: %{gap*100:.1f}  "
      f"{'Dikkat — model ezberliyor olabilir' if gap > 0.08 else 'Normal aralıkta'}")



#11. Görsel Çıktılar


# Confusion Matrix
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Sağlıklı", "Kriz"],
            yticklabels=["Sağlıklı", "Kriz"])
plt.title(f"Confusion Matrix  (eşik={threshold:.3f})")
plt.xlabel("Tahmin"); plt.ylabel("Gerçek")
plt.tight_layout()
plt.savefig("cm_sim_v1.png", dpi=120)
plt.show()

# ROC Eğrisi
plt.figure(figsize=(6, 5))
plt.plot(fpr, tpr, color='steelblue', lw=2, label=f"AUC = {roc_auc:.4f}")
plt.plot([0, 1], [0, 1], '--', color='gray')
plt.scatter([1 - specificity], [sensitivity], color='red', s=100, zorder=5,
            label=f"Seçilen eşik={threshold:.3f}  "
                  f"(recall={sensitivity:.3f}, precision={ppv:.3f})")
plt.xlabel("Yanlış Pozitif Oranı")
plt.ylabel("Duyarlılık")
plt.title("ROC Eğrisi")
plt.legend(fontsize=9)
plt.tight_layout()
plt.savefig("roc_sim_v1.png", dpi=120)
plt.show()

# Eğitim geçmişi grafikleri
fig, axes = plt.subplots(1, 3, figsize=(15, 4))
axes[0].plot(history.history['loss'],         label='Eğitim')
axes[0].plot(history.history['val_loss'],     label='Doğrulama')
axes[0].set_title("Kayıp (Focal Loss)"); axes[0].legend()

axes[1].plot(history.history['accuracy'],     label='Eğitim')
axes[1].plot(history.history['val_accuracy'], label='Doğrulama')
axes[1].set_title("Doğruluk")
axes[1].set_xlabel(f"Eğitim–Doğrulama farkı: %{gap*100:.1f}",
                   color='red' if gap > 0.08 else 'green')
axes[1].legend()

axes[2].plot(history.history['auc'],          label='Eğitim AUC')
axes[2].plot(history.history['val_auc'],      label='Doğrulama AUC')
axes[2].set_title("ROC AUC"); axes[2].legend()

plt.suptitle("Eğitim Geçmişi — Pre-Crisis Prediction",
             fontsize=12, fontweight='bold')
plt.tight_layout()
plt.savefig("training_sim_v1.png", dpi=120)
plt.show()

# Eşik analiz grafiği
fig, ax = plt.subplots(figsize=(10, 4))
ax.plot(tarama[:, 0], tarama[:, 1], label='Recall (Duyarlılık)', color='steelblue',  lw=2)
ax.plot(tarama[:, 0], tarama[:, 2], label='Precision (Kesinlik)', color='darkorange', lw=2)
ax.plot(tarama[:, 0], tarama[:, 3], label='F1 Skoru',             color='green',
        lw=1.5, linestyle='--')
ax.axhline(RECALL_HEDEF, color='red', linestyle=':', lw=1.5,
           label=f'Recall hedefi ({RECALL_HEDEF})')
ax.axvline(threshold, color='purple', linestyle='--', lw=2,
           label=f'Seçilen eşik = {threshold:.3f}')
ax.set_xlabel("Eşik Değeri"); ax.set_ylabel("Skor")
ax.set_title("Eşik Değeri Analizi")
ax.legend(fontsize=9); ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("threshold_sim_v1.png", dpi=120)
plt.show()



# ADIM 12 — Pre-Kriz Tahmin Görseli
# Test setinden bir kriz örneği alıp üç sinyali (HR, SpO2, EKG)
# zaman içinde çiziyoruz. Turuncu bölge modelin uyarı verdiği
# pre-kriz aşaması, kırmızı bölge krizin kendisi.


print("\n" + "=" * 60)
print("ADIM 12: PRE-KRİZ TAHMİN GÖRSELİ")
print("=" * 60)

test_kriz_idxler = [i for i in range(len(y_te)) if y_te[i] == 1]
test_ham_idxler  = np.where(test_mask)[0]

goster_idx  = test_kriz_idxler[min(2, len(test_kriz_idxler) - 1)]
ham_idx     = test_ham_idxler[goster_idx]
p_id        = patient_id[ham_idx]

if ham_idx in crisis_sample_index:
    ci_pos       = crisis_sample_index.index(ham_idx)
    crisis_start = crisis_start_times[ci_pos]
else:
    crisis_start = 30

pre_point = max(0, crisis_start - PRE_CRISIS_STEPS)

fig, axes = plt.subplots(3, 1, figsize=(14, 10), sharex=True)
fig.suptitle(
    f"Hasta {p_id} — Pre-Kriz Tahmin  |  "
    f"Bazal HR: {patient_hr_base[p_id]:.1f} bpm  |  "
    f"Bazal SpO2: {patient_spo2_base[p_id]:.1f} %  |  "
    f"Uyarı: {PRE_CRISIS_STEPS} dk önce",
    fontsize=13, fontweight='bold'
)

labels = ["HR (Nabız / bpm)", "SpO2 (Oksijen / %)", "EKG (mV)"]
colors = ["steelblue", "darkorange", "green"]
bazal  = [patient_hr_base[p_id], patient_spo2_base[p_id], None]

for i, (lbl, col) in enumerate(zip(labels, colors)):
    axes[i].plot(X_raw[ham_idx, :, i], color=col, lw=1.8, label=lbl)

    if bazal[i] is not None:
        axes[i].axhline(y=bazal[i], color=col, linestyle=':', alpha=0.5,
                        label="Kişisel Bazal")

    axes[i].axvspan(pre_point, crisis_start, alpha=0.20, color='orange',
                    label="Pre-kriz (uyarı bölgesi)" if i == 0 else "")
    axes[i].axvspan(crisis_start,
                    min(crisis_start + 15, TIME_STEPS),
                    alpha=0.20, color='red',
                    label="Kriz" if i == 0 else "")

    axes[i].axvline(x=pre_point,    color='orange', linestyle='--', lw=2)
    axes[i].axvline(x=crisis_start, color='red',    linestyle='--', lw=2)
    axes[i].set_ylabel(lbl, fontsize=9)
    axes[i].legend(loc='upper left', fontsize=8)

axes[2].set_xlabel("Zaman (dakika)")

x_norm_sample = X_norm[ham_idx]
score = float(model.predict(x_norm_sample[np.newaxis], verbose=0)[0][0])
alarm = score > threshold

axes[0].annotate(
    f"MODEL UYARISI\n{PRE_CRISIS_STEPS} dk önce\nGüven: %{score*100:.0f}",
    xy=(pre_point, axes[0].get_ylim()[1] * 0.92),
    fontsize=9,
    color='darkorange',
    fontweight='bold',
    bbox=dict(boxstyle='round,pad=0.3', facecolor='#fff3cd', edgecolor='orange')
)
axes[0].annotate(
    "KRİZ BAŞLADI",
    xy=(crisis_start + 1, axes[0].get_ylim()[1] * 0.92),
    fontsize=9,
    color='red',
    fontweight='bold',
    bbox=dict(boxstyle='round,pad=0.3', facecolor='#fde8e8', edgecolor='red')
)

plt.tight_layout()
plt.savefig("pre_crisis_gorsel_sim_v1.png", dpi=120)
plt.show()
print(f"  Görsel kaydedildi.")
print(f"  Model skoru: {score:.3f}  |  Alarm: {'EVET' if alarm else 'HAYIR'}")


#13. Dashboard

def draw_gauge(ax, value, vmin, vmax, normal_max, title, unit, color):
    val_c = np.clip(value, vmin, vmax)
    theta = np.pi + (0 - np.pi) * (val_c - vmin) / (vmax - vmin)
    t_arc = np.linspace(np.pi, 0, 200)
    ax.plot(np.cos(t_arc), np.sin(t_arc), color='#e0e0e0', lw=12,
            solid_capstyle='round')
    norm_f = np.clip((normal_max - vmin) / (vmax - vmin), 0, 1)
    t_n = np.linspace(np.pi, np.pi * (1 - norm_f), 200)
    ax.plot(np.cos(t_n), np.sin(t_n), color='#4caf50', lw=12,
            solid_capstyle='round')
    t_r = np.linspace(np.pi * (1 - norm_f), 0, 200)
    ax.plot(np.cos(t_r), np.sin(t_r), color='#f44336', lw=12,
            solid_capstyle='round')
    ax.annotate('', xy=(np.cos(theta) * .75, np.sin(theta) * .75),
                xytext=(0, 0),
                arrowprops=dict(arrowstyle='->', color=color, lw=3))
    ax.plot(0, 0, 'o', color=color, markersize=8)
    ax.text(0, -0.25, f"{value:.1f} {unit}", ha='center', va='center',
            fontsize=12, fontweight='bold', color=color)
    ax.text(0, -0.55, title, ha='center', va='center',
            fontsize=10, color='#333')
    ax.text(-1.05, -0.1, f"{vmin:.0f}", ha='center', fontsize=8, color='#888')
    ax.text( 1.05, -0.1, f"{vmax:.0f}", ha='center', fontsize=8, color='#888')
    ax.set_xlim(-1.2, 1.2); ax.set_ylim(-0.7, 1.1); ax.axis('off')


def normalize_sample(x_raw, p_idx):
    """Ham sensör değerini modelin beklediği formata çevirir."""
    x = x_raw.copy()
    x[:, 0] = (x[:, 0] - patient_hr_base[p_idx])   / HR_SCALE
    x[:, 1] = (x[:, 1] - patient_spo2_base[p_idx]) / SPO2_SCALE
    x[:, 2] =  x[:, 2]                              / ECG_SCALE
    return np.clip(x, -4, 4)


kriz_idx   = np.where(y == 1)[0][2]
normal_idx = np.where(y == 0)[0][3]

for dash_idx, dash_label in [(kriz_idx, 1), (normal_idx, 0)]:
    p_dash   = patient_id[dash_idx]
    hr_now   = X_raw[dash_idx, -1, 0]
    spo2_now = X_raw[dash_idx, -1, 1]
    ecg_now  = X_raw[dash_idx, -1, 2]

    x_dash = normalize_sample(X_raw[dash_idx], p_dash)
    score  = float(model.predict(x_dash[np.newaxis], verbose=0)[0][0])
    is_risk    = score > threshold
    status_txt = "KRİZ GELİYOR" if is_risk else "SAĞLIKLI"
    status_col = "#e74c3c" if is_risk else "#27ae60"
    bg_col     = "#fff5f5" if is_risk else "#f0fff4"

    fig = plt.figure(figsize=(16, 7), facecolor=bg_col)
    fig.suptitle(
        f"HASTA MONİTÖRÜ — Hasta {p_dash}  |  "
        f"Bazal HR: {patient_hr_base[p_dash]:.1f} bpm  |  "
        f"Bazal SpO2: {patient_spo2_base[p_dash]:.1f} %  |  "
        f"Pre-crisis {PRE_CRISIS_STEPS} dk",
        fontsize=13, fontweight='bold', color='#222'
    )
    gs = gridspec.GridSpec(2, 4, figure=fig, hspace=0.5, wspace=0.4)

    ax_hr     = fig.add_subplot(gs[0, 0])
    hr_esik   = patient_hr_base[p_dash] * 1.20
    gc        = '#e74c3c' if hr_now > hr_esik else '#27ae60'
    draw_gauge(ax_hr, hr_now, 40, 160, hr_esik, "Nabız (HR)", "bpm", gc)

    ax_spo2   = fig.add_subplot(gs[0, 1])
    spo2_esik = patient_spo2_base[p_dash] * 0.96
    gc2       = '#e74c3c' if spo2_now < spo2_esik else '#27ae60'
    draw_gauge(ax_spo2, spo2_now, 85, 100, spo2_esik, "SpO2 (%)", "%", gc2)

    ax_dec = fig.add_subplot(gs[0, 2])
    ax_dec.set_facecolor(bg_col)
    ax_dec.text(0.5, 0.68, status_txt, ha='center', va='center',
                fontsize=15, fontweight='bold', color=status_col,
                transform=ax_dec.transAxes,
                bbox=dict(boxstyle='round,pad=0.6', facecolor='white',
                          edgecolor=status_col, lw=2))
    ax_dec.text(0.5, 0.40, f"Güven: %{score*100:.1f}",
                ha='center', va='center', fontsize=12,
                color='#555', transform=ax_dec.transAxes)
    ax_dec.text(0.5, 0.24, f"Uyarı süresi: {PRE_CRISIS_STEPS} dakika",
                ha='center', va='center', fontsize=9,
                color='#888', transform=ax_dec.transAxes)
    ax_dec.text(0.5, 0.10, f"Eşik: {threshold:.3f}",
                ha='center', va='center', fontsize=8,
                color='#aaa', transform=ax_dec.transAxes)
    ax_dec.axis('off')
    ax_dec.set_title("Model Kararı", fontsize=10, pad=6)

    ax_num = fig.add_subplot(gs[0, 3])
    ax_num.axis('off'); ax_num.set_facecolor(bg_col)
    rows = [
        ["HR",   f"{hr_now:.1f} bpm",   f"{patient_hr_base[p_dash]:.1f} bpm"],
        ["SpO2", f"{spo2_now:.1f} %",   f"{patient_spo2_base[p_dash]:.1f} %"],
        ["EKG",  f"{ecg_now:.2f} mV",   "–"],
        ["Skor", f"{score:.3f}",         f"Eşik: {threshold:.3f}"],
    ]
    tbl = ax_num.table(cellText=rows,
                       colLabels=["Sinyal", "Anlık", "Kişisel Bazal"],
                       loc='center', cellLoc='center')
    tbl.auto_set_font_size(False); tbl.set_fontsize(9); tbl.scale(1.1, 1.6)
    ax_num.set_title("Anlık Değerler", fontsize=10, pad=6)

    sig_lbl = ["HR (bpm)", "SpO2 (%)", "EKG (mV)"]
    sig_col = ["steelblue", "darkorange", "green"]
    for si in range(3):
        ax_s = fig.add_subplot(gs[1, si])
        ax_s.plot(X_raw[dash_idx, :, si], color=sig_col[si], lw=1.5)

        if dash_label == 1 and dash_idx in crisis_sample_index:
            ci_d  = crisis_sample_index.index(dash_idx)
            cs    = crisis_start_times[ci_d]
            pre_s = max(0, cs - PRE_CRISIS_STEPS)
            ax_s.axvspan(pre_s, cs, alpha=0.15, color='orange')
            ax_s.axvspan(cs, min(cs + 15, TIME_STEPS), alpha=0.15, color='red')
            ax_s.axvline(x=pre_s, color='orange', linestyle='--', lw=1.5)
            ax_s.axvline(x=cs,    color='red',    linestyle='--', lw=1.5)

        ax_s.set_title(sig_lbl[si], fontsize=9, pad=3)
        ymin   = np.min(X_raw[dash_idx, :, si])
        ymax   = np.max(X_raw[dash_idx, :, si])
        margin = (ymax - ymin) * 0.1 if ymax != ymin else 1.0
        ax_s.set_ylim(ymin - margin, ymax + margin)

        if si == 0:
            ax_s.axhline(y=patient_hr_base[p_dash],
                         color='blue', linestyle=':', alpha=0.5, label="Bazal")
            ax_s.legend(fontsize=7)
        if si == 1:
            ax_s.axhline(y=patient_spo2_base[p_dash],
                         color='darkorange', linestyle=':', alpha=0.5, label="Bazal")
            ax_s.legend(fontsize=7)

    ax_auc = fig.add_subplot(gs[1, 3])
    ax_auc.axis('off'); ax_auc.set_facecolor(bg_col)
    info = (
        f"Model Performansı\n\n"
        f"ROC AUC      : {roc_auc:.4f}\n"
        f"Duyarlılık   : {sensitivity:.3f}\n"
        f"Özgüllük     : {specificity:.3f}\n"
        f"Kesinlik     : {ppv:.3f}\n"
        f"Kaçırılan    : {fn}\n"
        f"Yakalanan    : {tp_val}\n\n"
        f"Pre-crisis: {PRE_CRISIS_STEPS} dk\n"
        f"Simülasyon — MIMIC-III bekleniyor"
    )
    ax_auc.text(0.5, 0.5, info, ha='center', va='center',
                fontsize=9, transform=ax_auc.transAxes, color='#333',
                bbox=dict(boxstyle='round,pad=0.6', facecolor='white',
                          edgecolor='#ccc', lw=1))
    ax_auc.set_title("Sistem Özeti", fontsize=10, pad=6)

    lbl_str = "KRIZ" if dash_label == 1 else "NORMAL"
    fname   = f"dashboard_sim_v1_{lbl_str}.png"
    plt.savefig(fname, dpi=120, bbox_inches='tight', facecolor=bg_col)
    plt.show()
    print(f"  Dashboard kaydedildi: {fname}")



#14.Modeli Kaydet


model.save("bileklik_pre_crisis_sim_v1.keras")
print("\nModel kaydedildi: bileklik_pre_crisis_sim_v1.keras")
print("\n" + "=" * 60)
print("TAMAMLANDI — Pre-Crisis Prediction Simülasyon v1")
print(f"Kriz uyarı süresi: {PRE_CRISIS_STEPS} dakika")
print("MIMIC-III erişimi onaylandığında bu pipeline gerçek veriyle çalışacak.")
print("=" * 60)